### ISSUE TITLE
Champion object id, key

### ISSUE THREAD

**Issue by dp0973** [Canisback/static-data#1]
I wanna use champion id (ex. AurelionSol) but I found that key (ex. 136) was stored in "id" attribute and no attribute for original id in Champion object. Is there any reason for this?
```
class Champion(DataStore):
    BASE_URL = "http://ddragon.leagueoflegends.com/cdn/"
    
    def __init__(self, data):
        self.data = {
            "image" : data["image"],
            "name" : data["name"],
            "id":data["key"],
```

**Comment by Canisback** [comment]
Consistency between all classes, considering ddragon is too messy to do it natively.

**Comment by dp0973** [comment]
So sad but agree with that...

**Comment by dp0973** [comment]
So no plan for change yet?

**Comment by Canisback** [comment]
Why would I remove a feature fixing dragon lack of consistency?

**Comment by dp0973** [comment]
I solved it by some module customization for me. Thanks for your help!
